=  Landing Site and Knocki (R) WebApp
:imagesdir: Images/

__"Opportunity doesn't knock twice"__

'''

This is the landing site of a fictitious company named "IADS" and a WebApp to control a https://knocki.com[Knocki(R)] device.

These were built from the ground up, applying User Design Conventions and building up from Material Design guidelines. 
The landing site is a logbook of the techniques applied.

== Gallery

image::Screenshot(46).png[DEMO,300] image::Screenshot(47).png[DEMO,300] image::Screenshot(48).png[DEMO,300]
image::Screenshot(49).png[DEMO,300] image::Screenshot(50).png[DEMO,300]


== Contributors 

* Ángel Heredia Vázquez with the help of https://github.com/Mauville/AutoGit[AutoGit]
* Repo Owner

== For Recruiters
=== Concepts Applied

* Web Responsiveness
* Personas
* Benchmarking
* Prototyping
* Think Aloud Evaluation Techniques
* Material Design
* Local Storage
* JQuery


== Legal Disclaimer
We are in no way, related or associated with the Knocki(R) device and trademark nor Swan Solutions Inc. +
This was an educative design practice done under the Fair Use Act. No copyright infringement is intended.
